/**
 * app/manifest.ts
 *
 * PWA Web App Manifest — served as /manifest.json.
 * References the icon sizes generated by icon.tsx / apple-icon.tsx so that
 * "Add to Home Screen" on Android/iOS uses the correct MERNShop brand icon.
 */
import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "MERNShop",
    short_name: "MERNShop",
    description: "Discover premium products across electronics, fashion, books, and lifestyle.",
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#3b82f6",
    orientation: "portrait",
    icons: [
      {
        src: "/icon.png",
        sizes: "32x32",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/apple-icon.png",
        sizes: "180x180",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/favicon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
    ],
    categories: ["shopping", "lifestyle"],
  };
}
